name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Runs every day at 2:00 UTC == 3:00 AM UTC+1 (your local time)
    - cron: "0 2 * * *"
  workflow_dispatch: # allows manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name "OnuegbuUdochukwu"
          git config user.email "onuegbuudochukwu6@gmail.com"
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
